In [1]:
import numpy as np

In [2]:
x = np.random.random(1000)

In [3]:
x

array([5.35801670e-01, 6.56896324e-01, 6.58158479e-01, 5.02638297e-01,
       6.77323118e-01, 8.80912010e-01, 6.43152018e-01, 6.70404167e-01,
       3.84807853e-01, 3.88136659e-02, 7.10716872e-01, 2.15990208e-01,
       5.76855494e-01, 1.06621249e-01, 3.42520954e-01, 3.66206801e-01,
       8.39715230e-01, 3.85858686e-01, 1.15847939e-01, 3.56402842e-01,
       8.49039542e-01, 8.32265546e-01, 3.78801714e-01, 9.02425444e-01,
       8.70870084e-01, 4.28194746e-02, 1.81429210e-01, 3.95536213e-01,
       6.28091763e-01, 5.92187714e-01, 5.18175727e-01, 6.30783240e-01,
       3.89577474e-01, 5.25516565e-01, 1.92975772e-01, 7.50095939e-01,
       6.18094418e-02, 8.31846099e-01, 3.15803238e-01, 4.81897164e-01,
       4.23860575e-01, 1.51333941e-02, 2.02015792e-01, 4.44662377e-01,
       5.63483919e-01, 4.38735471e-01, 1.07738228e-01, 2.94456341e-01,
       3.34128479e-01, 7.70800215e-01, 1.86904883e-01, 8.46539396e-01,
       3.29984448e-01, 5.78737979e-01, 7.92492926e-01, 8.84339280e-01,
      

In [8]:
#Find Minimum Value
np.min(x)

0.0004939365578925381

In [9]:
#Find Minimum Value
x.min()

0.0004939365578925381

In [10]:
#Find Maximum Value
x.max()

0.9978594173813

In [11]:
#Find Sum of X
x.sum()

500.79694735631756

In [12]:
#Find Mean of X
x.mean()

0.5007969473563175

In [13]:
#Find Standard deviation of X
x.std()

0.2877186989096754

In [14]:
#Find Index of Minimum Value
x.argmin()

459

In [15]:
#Find Index of Maximum Value
x.argmax()

621

In [19]:
#compute percentile
np.percentile(x,25)

0.24781452259571465

In [20]:
#compute percentile
np.percentile(x,50)

0.5182291744214627

In [21]:
#Find Median
np.median(x)

0.5182291744214627

In [22]:
y = np.random.random((20,30))

In [23]:
y

array([[5.27890099e-01, 9.44267315e-02, 8.75882007e-01, 2.20035766e-01,
        3.63704139e-01, 9.14615880e-01, 4.99655762e-01, 2.21682634e-01,
        8.25421661e-01, 8.89218846e-01, 8.18158276e-01, 7.81280540e-01,
        7.78902116e-01, 1.05571926e-01, 7.81314093e-01, 4.35828469e-01,
        9.66164186e-01, 3.86285936e-01, 6.66145537e-01, 4.04555568e-01,
        7.10380921e-01, 9.22350361e-01, 4.29750023e-01, 3.19457456e-01,
        2.39466391e-01, 6.65954844e-01, 5.18119876e-01, 1.55705389e-01,
        8.79636073e-01, 3.10647293e-01],
       [7.87874809e-01, 4.83150403e-01, 6.49311389e-01, 5.26500233e-01,
        5.79978208e-01, 9.81635377e-01, 3.68472708e-01, 6.29138262e-01,
        8.05640874e-02, 5.04892536e-01, 2.46239866e-01, 1.96180541e-01,
        6.11592109e-02, 6.95548033e-01, 8.70753261e-01, 7.75629601e-01,
        6.86040078e-01, 1.94905583e-02, 3.49390306e-02, 9.71385007e-03,
        1.91288315e-01, 8.17365488e-01, 7.37311646e-01, 4.54813107e-01,
        4.51411191e-01,

In [24]:
y = np.random.random((3,5))

In [25]:
y

array([[0.69914589, 0.85115805, 0.18308911, 0.5690037 , 0.52455056],
       [0.44158898, 0.62563701, 0.38187806, 0.87002061, 0.5890155 ],
       [0.3476403 , 0.04919031, 0.25779744, 0.76270115, 0.40518865]])

In [31]:
#max value mulai axis 0 per kolom
np.max(y,axis=0)

array([0.69914589, 0.85115805, 0.38187806, 0.87002061, 0.5890155 ])

In [32]:
#max value mulai axis 0 per baris
np.max(y,axis=1)

array([0.85115805, 0.87002061, 0.76270115])