In [1]:
import numpy as np

In [19]:
x = np.arange(6)

In [20]:
x

array([0, 1, 2, 3, 4, 5])

In [21]:
# kurang dari menggunakan "<"
x<3

array([ True,  True,  True, False, False, False])

In [22]:
# Lebih dari menggunakan ">"
x>3

array([False, False, False, False,  True,  True])

In [23]:
# Lebih dari samadengan menggunakan ">="
x>=3

array([False, False, False,  True,  True,  True])

In [24]:
# samadengan menggunakan "=="
x==3

array([False, False, False,  True, False, False])

In [25]:
# tidak samadengan menggunakan "!="
x!=3

array([ True,  True,  True, False,  True,  True])

In [27]:
#untuk mengambil subset tertentu dalam array
x[x!=3]

array([0, 1, 2, 4, 5])