In [1]:
# Broadcasting Operation :
# 1. untuk memproses Array yang memiliki ukuran yang beda
# 2. extend ukuran suatu array agar sesuai dgn array lainnya

In [2]:
import numpy as np

In [17]:
# RULE 1 BROADCASTING

In [6]:
x = np.array([1,2,3])

In [7]:
x

array([1, 2, 3])

In [8]:
z = 5

In [9]:
x+z

array([6, 7, 8])

In [10]:
z = [1,2,3,4]

In [13]:
z = np.reshape(z,[2,2])

In [14]:
z

array([[1, 2],
       [3, 4]])

In [15]:
a = 5

In [16]:
z+a

array([[6, 7],
       [8, 9]])

In [18]:
# RULE 2 BROADCASTING

In [19]:
M = np.ones((2,3))
Q = np.arange(3)

In [20]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
Q

array([0, 1, 2])

In [22]:
M + Q

array([[1., 2., 3.],
       [1., 2., 3.]])

In [23]:
R = np.arange(3).reshape(3,1)

In [24]:
Q + R

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [25]:
R

array([[0],
       [1],
       [2]])

In [26]:
# Tidak semua bisa di broadcasting
# 1. Jika Dimensi tidak cocok
# 2. Juka Dimensi tidak ada yang bisa duplikat

In [27]:
S = np.arange(2,4)

In [28]:
S + R

array([[2, 3],
       [3, 4],
       [4, 5]])

In [29]:
S + Q

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [30]:
# Diatas contoh ketika broadcasting tidak bisa dilakukan